apiVersion: apps/v1
kind: Deployment
metadata:
    name: gateway
spec:
    replicas: 2
    selector:
        matchLabels:
            app: gateway
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 3
    template:
        metadata:
            labels:
                app: gateway
        spec:
            containers:
                - name: gateway
                  image: valkyraycho/mp3converter-gateway
                  envFrom:
                      - configMapRef:
                            name: gateway-configmap
                      - secretRef:
                            name: gateway-secret
